package com.thingworx.things.agent.cache;

import java.util.Objects;

/**
 * Core-created access context for one ArtifactCache operation. Carries the current ThingWorx
 * principal and a Core-generated opaque caller scope; model/App inputs cannot supply either.
 * Namespace equality is the principal/scope pair; {@link #namespaceKey()} is an injective
 * encoding of that pair for concurrent-index maps.
 */
public final class ArtifactAccessContext {

    private final String principalName;
    private final String opaqueScopeId;
    private final String namespaceKey;

    ArtifactAccessContext(String principalName, String opaqueScopeId) {
        this.principalName = Objects.requireNonNull(principalName, "principalName");
        this.opaqueScopeId = Objects.requireNonNull(opaqueScopeId, "opaqueScopeId");
        if (principalName.isEmpty()) {
            throw new IllegalArgumentException("principalName must be non-empty");
        }
        if (opaqueScopeId.isEmpty()) {
            throw new IllegalArgumentException("opaqueScopeId must be non-empty");
        }
        this.namespaceKey = encodeNamespaceKey(principalName, opaqueScopeId);
    }

    /**
     * Injective namespace map key: {@code <principalLength>\u0001<principal>\u0001<scope>}.
     * Length-prefix prevents delimiter collision between principal and scope components.
     */
    static String encodeNamespaceKey(String principalName, String opaqueScopeId) {
        return principalName.length() + "\u0001" + principalName + '\u0001' + opaqueScopeId;
    }

    /** Current ThingWorx security principal name captured by Core. */
    public String principalName() {
        return principalName;
    }

    /** Opaque caller scope identity generated by Core (not a model/App-submitted id). */
    public String opaqueScopeId() {
        return opaqueScopeId;
    }

    /**
     * Stable injective key for current-JVM index namespace separation. Distinct principal/scope
     * pairs never share a key, including when components contain {@code \u0001}.
     */
    public String namespaceKey() {
        return namespaceKey;
    }

    /** True only when both principal and opaque scope match. */
    public boolean sameNamespace(ArtifactAccessContext other) {
        return other != null
                && principalName.equals(other.principalName)
                && opaqueScopeId.equals(other.opaqueScopeId);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) {
            return true;
        }
        if (!(o instanceof ArtifactAccessContext)) {
            return false;
        }
        ArtifactAccessContext that = (ArtifactAccessContext) o;
        return principalName.equals(that.principalName) && opaqueScopeId.equals(that.opaqueScopeId);
    }

    @Override
    public int hashCode() {
        return Objects.hash(principalName, opaqueScopeId);
    }

    @Override
    public String toString() {
        return "ArtifactAccessContext{principal=" + principalName + ", scope=" + opaqueScopeId + '}';
    }
}
