/**
 * ThingWorx widget extension package version (Composer import), from `parler-ui-widget/input/widgets.json`.
 * Regenerated by `npm run build:tw` and by `parler-ui-widget` `npm run sync` — do not edit by hand.
 */
export const WIDGET_PACKAGE_VERSION = "0.1.98";
